<<<<<<< HEAD
# Generated by Django 5.2.9 on 2025-12-11 18:43

=======
# Generated by Django 5.2.9 on 2025-12-13 16:42

import django.db.models.deletion
from django.conf import settings
>>>>>>> f9ab2a26f914e776428e2c1383a3ef813a0d9112
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> f9ab2a26f914e776428e2c1383a3ef813a0d9112
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
            ],
=======
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('carpentry', 'Carpentry'), ('cleaning', 'Cleaning'), ('tutoring', 'Tutoring'), ('hvac', 'HVAC'), ('roofing', 'Roofing'), ('landscaping', 'Landscaping'), ('painting', 'Painting'), ('other', 'Other')], default='other', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('business_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('service_description', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Profile',
                'verbose_name_plural': 'Provider Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
>>>>>>> f9ab2a26f914e776428e2c1383a3ef813a0d9112
        ),
    ]
