# Generated by Django 5.2.9 on 2025-12-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='services_rendered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
