# Generated by Django 5.2.9 on 2025-12-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_providerprofile_bio_providerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
