# Generated by Django 5.2.9 on 2025-12-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_providerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Provider Profile', 'verbose_name_plural': 'Provider Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
