# Generated by Django 6.0 on 2026-01-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_providerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude for live tracking', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude for live tracking', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum service price', max_digits=10),
        ),
    ]
