# Generated by Django 5.2.9 on 2026-01-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_providerprofile_latitude_providerprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum service price (for display range)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_rate',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed Price'), ('custom', 'Custom Quote')], default='fixed', help_text='How this provider charges for services', max_length=20),
        ),
    ]
