# Generated by Django 6.0 on 2026-01-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_update_decline_reason_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price offered by the user', max_digits=10, null=True),
        ),
    ]
