# Generated by Django 5.2.9 on 2026-01-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_servicerequest_offered_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='email_read_timestamp',
            field=models.DateTimeField(blank=True, help_text='When provider opened email (if tracked)', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email_response_timestamp',
            field=models.DateTimeField(blank=True, help_text='When provider responded to request', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email_sent_to_provider',
            field=models.BooleanField(default=False, help_text='Whether provider notification email was sent'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email_sent_to_provider_timestamp',
            field=models.DateTimeField(blank=True, help_text='When provider email was sent', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email_sent_to_user',
            field=models.BooleanField(default=False, help_text='Whether user notification email was sent'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email_sent_to_user_timestamp',
            field=models.DateTimeField(blank=True, help_text='When user email was sent', null=True),
        ),
    ]
