# Generated by Django 5.2.9 on 2026-01-13 07:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_servicerequest_email_read_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the job was marked as completed')),
                ('completion_notes', models.TextField(blank=True, help_text='Optional notes about the job completion')),
                ('work_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], help_text="User's assessment of work quality", max_length=20, null=True)),
                ('completed_on_time', models.BooleanField(default=True, help_text='Whether the job was completed on schedule')),
                ('provider_showed_up', models.BooleanField(default=True, help_text='Whether the provider showed up as scheduled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(help_text='User who marked the job as complete', on_delete=django.db.models.deletion.CASCADE, related_name='completed_jobs', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(help_text='The service request that was completed', on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='requests.servicerequest')),
            ],
            options={
                'verbose_name': 'Job Completion',
                'verbose_name_plural': 'Job Completions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('compliment', 'Compliment'), ('issue', 'Issue Report')], default='general', help_text='Type of feedback', max_length=20)),
                ('feedback_text', models.TextField(help_text='Feedback content', max_length=2000)),
                ('category', models.CharField(choices=[('quality', 'Work Quality'), ('timing', 'Timing/Schedule'), ('communication', 'Communication'), ('pricing', 'Pricing'), ('professionalism', 'Professionalism'), ('platform', 'Platform Experience'), ('other', 'Other')], default='other', help_text='Category of feedback', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of this feedback', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('addressed', 'Addressed'), ('closed', 'Closed')], default='new', help_text='Status of feedback processing', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Administrative response to feedback')),
                ('admin_response_date', models.DateTimeField(blank=True, help_text='When admin responded', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_response_by', models.ForeignKey(blank=True, help_text='Admin who responded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(help_text='Service request this feedback is about', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='requests.servicerequest')),
                ('submitted_by', models.ForeignKey(help_text='User who submitted the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Feedback',
                'verbose_name_plural': 'Service Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(help_text='Star rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(help_text="User's written feedback about the service", max_length=1000)),
                ('quality_rating', models.IntegerField(blank=True, help_text='Rating for quality of work (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_rating', models.IntegerField(blank=True, help_text='Rating for timeliness (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(blank=True, help_text='Rating for communication (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.IntegerField(blank=True, help_text='Rating for professionalism (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_recommend', models.BooleanField(default=True, help_text='Would the user recommend this provider to others')),
                ('would_hire_again', models.BooleanField(default=True, help_text='Would the user hire this provider again')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this rating should be shown publicly')),
                ('provider_response', models.TextField(blank=True, help_text="Provider's response to the rating", max_length=500)),
                ('provider_response_date', models.DateTimeField(blank=True, help_text='When provider responded to the rating', null=True)),
                ('job_completion', models.OneToOneField(help_text='The job completion this rating is for', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='requests.jobcompletion')),
                ('provider', models.ForeignKey(help_text='Provider who received this rating', on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('rated_by', models.ForeignKey(help_text='User who submitted this rating', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Rating',
                'verbose_name_plural': 'Service Ratings',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
