# Generated by Django 5.2.9 on 2026-01-19 20:03

import requests.file_validation
import requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_jobcompletion_servicefeedback_servicerating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request Photo', 'verbose_name_plural': 'Request Photos'},
        ),
        migrations.AddField(
            model_name='requestphoto',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='requestphoto',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original uploaded filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='requestphoto',
            name='image',
            field=models.ImageField(help_text='Upload request photo (JPG, PNG, GIF, WEBP). Max size: 5MB, Max dimensions: 4096x4096px', upload_to=requests.models.secure_photo_upload_path, validators=[requests.file_validation.validate_request_photo]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
