# Generated by Django 5.2.9 on 2026-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_add_geolocation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance from user to provider in kilometers (calculated using Haversine formula)', max_digits=6, null=True),
        ),
    ]
