# Generated by Django 5.2.9 on 2026-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_add_distance_and_urgent_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When user marked the job as completed', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, help_text='When provider started working on the request', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('declined', 'Declined'), ('completed', 'Completed'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
